steps:
  - name: install
    run: pip install -r requirements.txt
  - name: train
    run: python train.py
  - name: evaluate
    run: python evaluate.py
  - name: deploy
    run: python validate_deploy.py